### ISSUE TITLE
Cool project opportunity :)

### ISSUE THREAD

**Issue by musashi-glitch** [alecananian/strava-activity-map#16]
Hey Alec! I saw that you're contributing to the Treasure ecosystem and wanted to see if you'd be interested in a new opportunity. I recently raised a seed round to build a web3 creative studio. Our goal is to release viral product drops where people can earn digital collectibles and exclusive rewards. We have a world-class design team and are looking for someone to lead frontend. Lmk if you're interested! Feel free to email me patrick.x.rivera@gmail.com or find me on [Twitter](https://twitter.com/patrickxrivera).

**Comment by alecananian** [comment]
This is a hilarious strategy, but no thank you.
